version: '3.7'

services:
    digirentdb:
        image: mdillon/postgis:11-alpine
        container_name: digirentdb
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - "5432"
        env_file:
            - env/.db.staging.env
        restart: unless-stopped
    digirent-api:
        image: ghcr.io/ariento89/digirent-api:staging
        container_name: digirent-api
        ports:
            - "5000:5000"
        env_file:
            - env/.staging.env
        depends_on:
            - digirentdb
        restart: unless-stopped
        command: ["uvicorn", "digirent.web_app:app", "--host", "0.0.0.0", "--port", "5000"]
    digirent-redis:
        container_name: digirent-redis
        image: redis:6.0.9-alpine
    digirent-rent-worker:
        image: ghcr.io/ariento89/digirent-api:staging
        container_name: digirent-rent-worker
        env_file:
            - env/.staging.env
        depends_on:
            - digirentdb
            - digirent-redis
        command: ["celery", "--app=digirent.worker.app:app", "worker", "-Q", "rent-queue", "-l", "info"]
    digirent-subscription-worker:
        image: ghcr.io/ariento89/digirent-api:staging
        container_name: digirent-subscription-worker
        env_file:
            - env/.staging.env
        depends_on:
            - digirentdb
            - digirent-redis
        command: ["celery", "--app=digirent.worker.app:app", "worker", "-Q", "subscription-queue", "-l", "info"]
    digirent-beat:
        image: ghcr.io/ariento89/digirent-api:staging
        container_name: digirent-beat
        env_file:
            - env/.staging.env
        depends_on:
            - digirent-subscription-worker
            - digirent-rent-worker
        command: ["celery", "--app=digirent.worker.app:app", "beat", "-l", "info"]
    digirent-app:
        image: ghcr.io/ariento89/digirent-app:staging
        container_name: digirent-app
        expose:
            - "3000"
        depends_on:
            - digirent-api
        env_file:
            - env/.web.staging.env
        command: bash -c "yarn start"
        restart: unless-stopped
    digirent-nginx:
        image: nginx:mainline-alpine
        container_name: digirent-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - web-root:/var/www/html
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        depends_on:
            - digirent-api
            - digirent-app
    digirent-certbot:
        image: certbot/certbot
        container_name: digirent-certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - digirent-nginx
        command: certonly --webroot --webroot-path=/var/www/html --email orelio.lopes@gmail.com --agree-tos --no-eff-email --force-renewal -d digi-rent.me -d www.digi-rent.me

volumes:
    postgres_data:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /root/Digirent/views
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: /root/Digirent/dhparam/
            o: bind
