"""Include spatial column on apartment

Revision ID: 062a4231f34d
Revises: c727dec91c91
Create Date: 2020-10-27 07:17:24.885880

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = "062a4231f34d"
down_revision = "c727dec91c91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apartments",
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
    )
    op.add_column("contracts", sa.Column("canceled", sa.Boolean(), nullable=False))
    op.add_column("contracts", sa.Column("canceled_on", sa.DateTime(), nullable=True))
    op.add_column("contracts", sa.Column("expired", sa.Boolean(), nullable=False))
    op.add_column("contracts", sa.Column("expired_on", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "expired_on")
    op.drop_column("contracts", "expired")
    op.drop_column("contracts", "canceled_on")
    op.drop_column("contracts", "canceled")
    op.drop_column("apartments", "location")
    # ### end Alembic commands ###
