"""new blog post and tag models

Revision ID: 1ffa3186eb5d
Revises: 2035a8d230ba
Create Date: 2021-01-03 09:55:54.826840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = "1ffa3186eb5d"
down_revision = "2035a8d230ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_posts",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "blog_tags",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "blog_posts_tags_association",
        sa.Column(
            "blog_post_id",
            UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column("blog_tag_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["blog_post_id"],
            ["blog_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["blog_tag_name"],
            ["blog_tags.name"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_posts_tags_association")
    op.drop_table("blog_tags")
    op.drop_table("blog_posts")
    # ### end Alembic commands ###
