"""include is_archived column on apartment

Revision ID: 2489196d5d49
Revises: e004cf216542
Create Date: 2021-03-07 10:17:04.332154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = "2489196d5d49"
down_revision = "e004cf216542"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    apartments_table = table("apartments", column("is_archived", sa.Boolean()))
    op.add_column("apartments", sa.Column("is_archived", sa.Boolean(), nullable=True))
    conn.execute(apartments_table.update().values({"is_archived": False}))
    op.alter_column("apartments", "is_archived", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apartments", "is_archived")
    # ### end Alembic commands ###
