"""redefine user model

Revision ID: 460e0e7baec7
Revises: 612ca02e7672
Create Date: 2020-09-29 08:52:06.558876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "460e0e7baec7"
down_revision = "612ca02e7672"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("dob", sa.Date(), nullable=True))
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.drop_column("users", "dob")
    # ### end Alembic commands ###
