"""define invoice model

Revision ID: 76080a524c19
Revises: 062a4231f34d
Create Date: 2020-11-02 22:18:25.031709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ChoiceType, UUIDType
from digirent.database.enums import InvoiceStatus, InvoiceType

# revision identifiers, used by Alembic.
revision = "76080a524c19"
down_revision = "062a4231f34d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("type", ChoiceType(InvoiceType, impl=sa.String()), nullable=False),
        sa.Column(
            "status", ChoiceType(InvoiceStatus, impl=sa.String()), nullable=False
        ),
        sa.Column(
            "apartment_application_id",
            UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column("user_id", UUIDType(binary=False), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("payment_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["apartment_application_id"],
            ["apartment_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invoices")
    # ### end Alembic commands ###
