"""include has_document on contract

Revision ID: 8f52c492d908
Revises: a28b39c95b06
Create Date: 2021-04-09 07:13:49.462921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = "8f52c492d908"
down_revision = "a28b39c95b06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    contract_table = table("contracts", column("has_document", sa.Boolean()))
    op.add_column("contracts", sa.Column("has_document", sa.Boolean(), nullable=True))
    conn.execute(contract_table.update().values({"has_document": True}))
    op.alter_column("contracts", "has_document", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "has_document")
    # ### end Alembic commands ###
