"""new notifications model

Revision ID: a28b39c95b06
Revises: 2489196d5d49
Create Date: 2021-03-16 15:25:30.530246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ChoiceType, JSONType, UUIDType
from digirent.database.enums import NotificationType


# revision identifiers, used by Alembic.
revision = "a28b39c95b06"
down_revision = "2489196d5d49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column(
            "type", ChoiceType(NotificationType, impl=sa.String()), nullable=False
        ),
        sa.Column("user_id", UUIDType(binary=False), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("data", JSONType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    # ### end Alembic commands ###
