"""define amenities model

Revision ID: b6299dde6105
Revises: e301535632fa
Create Date: 2020-10-02 12:45:33.397694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6299dde6105"
down_revision = "e301535632fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "apartments_amenities_association",
        sa.Column("apartment_id", UUIDType(binary=False), nullable=True),
        sa.Column("amenity_id", UUIDType(binary=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
        ),
    )
    op.drop_column("apartments", "amenities")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apartments",
        sa.Column(
            "amenities",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("apartments_amenities_association")
    op.drop_table("amenities")
    # ### end Alembic commands ###
