"""Define apartment application model

Revision ID: bb276adbfff8
Revises: b6299dde6105
Create Date: 2020-10-07 14:39:42.799541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType, ChoiceType
from digirent.database.enums import ApartmentApplicationStage

# revision identifiers, used by Alembic.
revision = "bb276adbfff8"
down_revision = "b6299dde6105"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apartment_applications",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("apartment_id", UUIDType(binary=False), nullable=False),
        sa.Column("tenant_id", UUIDType(binary=False), nullable=False),
        sa.Column(
            "stage",
            ChoiceType(ApartmentApplicationStage, impl=sa.String()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "apartment_id", "tenant_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("apartment_applications")
    # ### end Alembic commands ###
