"""new booking request model

Revision ID: cd76843d4ea4
Revises: bb276adbfff8
Create Date: 2020-10-10 09:15:43.032952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType, ChoiceType
from digirent.database.enums import FurnishType


# revision identifiers, used by Alembic.
revision = "cd76843d4ea4"
down_revision = "bb276adbfff8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_requests",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("tenant_id", UUIDType(binary=False), nullable=False),
        sa.Column("apartment_id", UUIDType(binary=False), nullable=False),
        sa.Column("apartment_application_id", UUIDType(binary=False), nullable=True),
        sa.Column("status", ChoiceType(FurnishType, impl=sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["apartment_application_id"],
            ["apartment_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booking_requests")
    # ### end Alembic commands ###
