"""update user model

Revision ID: cefa26545898
Revises: 460e0e7baec7
Create Date: 2020-09-29 16:02:00.674466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ChoiceType

from digirent.database.enums import Gender


# revision identifiers, used by Alembic.
revision = "cefa26545898"
down_revision = "460e0e7baec7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("city", sa.String(), nullable=True))
    op.add_column("users", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("gender", ChoiceType(Gender, impl=sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    op.drop_column("users", "description")
    op.drop_column("users", "city")
    # ### end Alembic commands ###
