"""Initial migration

Revision ID: df0c688043a1
Revises:
Create Date: 2020-10-17 19:37:51.237474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType, ChoiceType, EmailType
from digirent.database.enums import (
    UserRole,
    ApartmentApplicationStage,
    BookingRequestStatus,
    SocialAccountType,
    Gender,
    HouseType,
    FurnishType,
)

# revision identifiers, used by Alembic.
revision = "df0c688043a1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("email", EmailType(length=255), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column("suspended_reason", sa.String(), nullable=True),
        sa.Column("role", ChoiceType(UserRole, impl=sa.String()), nullable=False),
        sa.Column("gender", ChoiceType(Gender, impl=sa.String()), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "apartments",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("monthly_price", sa.Float(), nullable=False),
        sa.Column("utilities_price", sa.Float(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "house_type", ChoiceType(HouseType, impl=sa.String()), nullable=False
        ),
        sa.Column(
            "furnish_type", ChoiceType(FurnishType, impl=sa.String()), nullable=False
        ),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("bathrooms", sa.Integer(), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("available_from", sa.Date(), nullable=False),
        sa.Column("available_to", sa.Date(), nullable=False),
        sa.Column("landlord_id", UUIDType(binary=False), nullable=False),
        sa.Column("tenant_id", UUIDType(binary=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["landlord_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bank_details",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("user_id", UUIDType(binary=False), nullable=True),
        sa.Column("account_name", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "looking_for",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("tenant_id", UUIDType(binary=False), nullable=True),
        sa.Column(
            "house_type", ChoiceType(HouseType, impl=sa.String()), nullable=False
        ),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("max_budget", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "social_accounts",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("id_token", sa.String(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column(
            "account_type",
            ChoiceType(SocialAccountType, impl=sa.String()),
            nullable=False,
        ),
        sa.Column("user_id", UUIDType(binary=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
        sa.UniqueConstraint("id_token"),
    )
    op.create_table(
        "apartment_applications",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("apartment_id", UUIDType(binary=False), nullable=False),
        sa.Column("tenant_id", UUIDType(binary=False), nullable=False),
        sa.Column(
            "stage",
            ChoiceType(ApartmentApplicationStage, impl=sa.String()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apartments_amenities_association",
        sa.Column("apartment_id", UUIDType(binary=False), nullable=True),
        sa.Column("amenity_id", UUIDType(binary=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
        ),
    )
    op.create_table(
        "booking_requests",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("tenant_id", UUIDType(binary=False), nullable=False),
        sa.Column("apartment_id", UUIDType(binary=False), nullable=False),
        sa.Column("apartment_application_id", UUIDType(binary=False), nullable=True),
        sa.Column(
            "status", ChoiceType(BookingRequestStatus, impl=sa.String()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["apartment_application_id"],
            ["apartment_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booking_requests")
    op.drop_table("apartments_amenities_association")
    op.drop_table("apartment_applications")
    op.drop_table("social_accounts")
    op.drop_table("looking_for")
    op.drop_table("bank_details")
    op.drop_table("apartments")
    op.drop_table("users")
    op.drop_table("amenities")
    # ### end Alembic commands ###
