"""Define social accounts model

Revision ID: ed7925849116
Revises: cd76843d4ea4
Create Date: 2020-10-17 16:40:46.827129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType, ChoiceType
from digirent.database.enums import SocialAccountType


# revision identifiers, used by Alembic.
revision = "ed7925849116"
down_revision = "cd76843d4ea4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_accounts",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", UUIDType(binary=False), nullable=False),
        sa.Column("id_token", sa.String(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column(
            "account_type",
            ChoiceType(SocialAccountType, impl=sa.String()),
            nullable=False,
        ),
        sa.Column("user_id", UUIDType(binary=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
        sa.UniqueConstraint("id_token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("social_accounts")
    # ### end Alembic commands ###
